### ISSUE TITLE
Truncation Ellipses should use Ellipses character

### ISSUE THREAD

**Issue by rmccaskill** [carbon-design-system/carbon-website-archive#622]
## Detailed description

In the Overflow Content page the ellipses talked about in 'Truncation' (https://www.carbondesignsystem.com/patterns/overflow-content/#truncation) should be one ellipses character not three individual dot characters. 

'…' not '...'

You could us any of the following instead.
```
&hellip;
&#0133;
U+2026
```
Note: This is relevant to some screen readers so they don't read 'dot dot dot'

See https://tosbourn.com/the-importance-of-using-the-ellipsis-character/
https://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/

**Comment by jnm2377** [comment]
Hi @rmccaskill! :wave:  Thanks so much for taking the time to make this issue :smile:
I just wanted to get some clarification on which specific ellipsis instance you were talking about. 

> In the Overflow Content page the ellipses talked about in 'Truncation' (https://www.carbondesignsystem.com/patterns/overflow-content/#truncation) should be one ellipses character not three individual dot characters.

From your description, it seems like you are talking about the ellipsis in the below image. However, that ellipsis is an inline code-snippet, which is why I think it's utilizing ` ... ` rather than `&hellip;`. I believe it's meant to show users what the ellipsis looks like in a way that stands out from the rest of the text, rather than showing how to code in the ellipsis since it is not usually hard coded into the html.

<img width="686" alt="screen shot 2019-01-07 at 11 40 43 am" src="https://user-images.githubusercontent.com/32556167/50783862-97450c80-1271-11e9-91c0-d1fe4d103e39.png">

I think from your description, the first example of ellipsis below could probably use the ellipsis character rather than ... since it's not in a code snippet, but I think that may be a mistake on our end, seeing as the rest of the examples are in code snippets, that one should probably be too. I think another option that could be possible is instead of using an inline code snippet to emphasize the ellipsis, we could utilize the ellipsis character and style it to stand out? This way it's still accessible to screen readers but follows the visual purpose we want. Not sure what your thoughts are on that, @alisonjoseph.

<img width="669" alt="screen shot 2019-01-07 at 11 41 26 am" src="https://user-images.githubusercontent.com/32556167/50783867-9ad89380-1271-11e9-8463-32a2c521fe41.png">

**Comment by jnm2377** [comment]
Ah, @rmccaskill saw your PR. Will take a look at that!
